# Generated by Django 4.2.30 on 2026-10-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_merchantissuemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantissue',
            name='issue_type',
            field=models.CharField(choices=[('status_mismatch', 'Delivered, but a different status is shown'), ('payment_delayed', 'Delivered, but payment is delayed'), ('payment_missing', 'Payment not received or wrong amount'), ('tracking_stuck', 'Tracking is not updating'), ('rto_return', 'Return or RTO not reflected'), ('customer_dispute', 'Customer says the order was not delivered'), ('other', 'Something else')], db_index=True, max_length=40),
        ),
    ]
