# Generated by Django 4.2.30 on 2026-10-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_merchantissue_trim_issue_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantissue',
            name='report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
