# Generated by Django 4.2.30 on 2026-10-08 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0010_merchantissuenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('order_ref', models.CharField(db_index=True, max_length=80)),
                ('order', models.JSONField(blank=True, default=dict)),
                ('issue_type', models.CharField(choices=[('not_received', 'Order marked delivered but not received'), ('wrong_item', 'Received a wrong item'), ('damaged', 'Received a damaged item'), ('delayed', 'Order is delayed'), ('refund', 'Refund problem'), ('other', 'Something else')], db_index=True, max_length=40)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], db_index=True, default='new', max_length=20)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_customer_issue',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerIssueNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='adminpanel.customerissue')),
            ],
            options={
                'db_table': 'admin_customer_issue_note',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerIssueMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('admin', 'EscroSafe')], db_index=True, max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='adminpanel.customerissue')),
            ],
            options={
                'db_table': 'admin_customer_issue_message',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
