# Generated by Django 4.2.30 on 2026-10-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_customerissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerissue',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
