# Generated by Django 4.2.30 on 2026-10-08 13:03

import adminpanel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_customerissue_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerissue',
            name='details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CustomerIssueAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=adminpanel.models.customer_issue_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='adminpanel.customerissue')),
            ],
            options={
                'db_table': 'admin_customer_issue_attachment',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
